/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  "docs": {
    "概览": [
      "overview",
      "publications"
    ],
    "快速入门": [
      "getting-started"
    ],
    "编译 MISA-MD": [
      "prepare-environment",
      "get-source-code",
      "compiling",
      "compiling-with-hip",
      "compiling-with-sunway"
    ],
    "运行 MD": [
      "potential-file",
      "run-md"
    ],
    "配置": [
      "configure",
      "model-cascade-collision",
      "configure-terms"
    ],
    "工具": [
      "md-tools"
    ]
    //  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  },
}
