# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # see also: https://github.com/facebook/docusaurus/issues/2798#issuecomment-636602951

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.4.0'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --ignore-scripts 
        working-directory: ./
      - run: yarn build
        working-directory: ./
        env:
          CI: true
          DOC_DEPLOY_PATH: "/MDoc/"
          DOC_GIT_REPO: "https://github.com/misa-md/MDoc"
          DOC_SITE_URL: "https://misa-md.github.io"
          SOURCE_GIT_REPO: "https://github.com/misa-md/MISA-MD"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
